# Generated by Django 4.1 on 2023-01-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fnb_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.CharField(max_length=400)),
                ('startup_name', models.CharField(max_length=400)),
                ('web_link', models.CharField(max_length=400)),
                ('pvt_yn', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=1000)),
                ('contact', models.IntegerField()),
                ('city', models.CharField(max_length=400)),
                ('theme', models.CharField(max_length=400)),
                ('unique', models.CharField(max_length=1000)),
                ('stage', models.CharField(max_length=400)),
                ('validation', models.CharField(max_length=400)),
                ('patent', models.CharField(max_length=300)),
                ('incubated', models.CharField(max_length=300)),
                ('incubator_name', models.CharField(max_length=400)),
                ('looking_for', models.CharField(max_length=400)),
            ],
        ),
    ]
