# Generated by Django 4.1 on 2023-01-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pitch_submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_email', models.CharField(max_length=400)),
                ('pitch_link', models.CharField(max_length=400)),
                ('pitch_video', models.CharField(max_length=400)),
            ],
        ),
    ]
